Repository upscayl/upscayl, pull requests merged in 2024-09, with the labels that each got.

#950 Add Language Switcher
  electron/index.ts
  next.config.js
  package-lock.json
  package.json
  renderer/atoms/translations-atom.ts
  renderer/components/settings-tab/index.tsx
  renderer/components/settings-tab/language-switcher.tsx
  renderer/components/upscayl-tab/view/ProgressBar.tsx
  renderer/locales/en.json
  renderer/locales/ru.json
Labels: enhancement, size:L

#956 Delete flatpak directory
  flatpak/org.upscayl.Upscayl.json
  flatpak/org.upscayl.Upscayl.metainfo.xml
Labels: size:L

#983 Support JFIF files which are basically JPGs anyways
  electron/commands/select-file.ts
  renderer/locales/en.json
  renderer/locales/es.json
  renderer/locales/fr.json
  renderer/locales/ja.json
  renderer/locales/locale_template
  renderer/locales/ru.json
  renderer/locales/zh.json
  renderer/pages/index.tsx
Labels: enhancement, size:S
