Repository upscayl/upscayl, pull requests merged in 2025-01, with the labels that each got.

#1102 Add German translation de.json
  renderer/locales/de.json
Labels: enhancement, size:L, lgtm

#1107 Arabic Translation
  renderer/atoms/translations-atom.ts
  renderer/components/sidebar/settings-tab/language-switcher.tsx
  renderer/locales/ar.json
Labels: enhancement, size:L

#1125 Turkish Translation
  renderer/atoms/translations-atom.ts
  renderer/components/sidebar/settings-tab/language-switcher.tsx
  renderer/locales/tr.json
Labels: documentation, enhancement, size:L
